// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoliziaMunicipale.Data;

#nullable disable

namespace Progetto_Settimanale.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PoliziaMunicipale.Models.Anagrafica", b =>
                {
                    b.Property<int>("IdAnagrafica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnagrafica"));

                    b.Property<string>("CAP")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cod_Fisc")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAnagrafica");

                    b.ToTable("Anagrafiche");

                    b.HasData(
                        new
                        {
                            IdAnagrafica = 1,
                            CAP = "20100",
                            Citta = "Milano",
                            Cod_Fisc = "RSSMRA80A01F205X",
                            Cognome = "Rossi",
                            Indirizzo = "Via Roma 10",
                            Nome = "Mario"
                        },
                        new
                        {
                            IdAnagrafica = 2,
                            CAP = "10100",
                            Citta = "Torino",
                            Cod_Fisc = "BNCLCU85C10L219Q",
                            Cognome = "Bianchi",
                            Indirizzo = "Corso Italia 55",
                            Nome = "Luca"
                        });
                });

            modelBuilder.Entity("PoliziaMunicipale.Models.TipoViolazione", b =>
                {
                    b.Property<int>("IdViolazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdViolazione"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdViolazione");

                    b.ToTable("TipiViolazione");

                    b.HasData(
                        new
                        {
                            IdViolazione = 1,
                            Descrizione = "Eccesso di velocità oltre 10 km/h"
                        },
                        new
                        {
                            IdViolazione = 2,
                            Descrizione = "Guida senza cintura"
                        });
                });

            modelBuilder.Entity("PoliziaMunicipale.Models.Verbale", b =>
                {
                    b.Property<int>("IdVerbale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVerbale"));

                    b.Property<DateTime>("DataTrascrizioneVerbale")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataViolazione")
                        .HasColumnType("datetime2");

                    b.Property<int>("DecurtamentoPunti")
                        .HasColumnType("int");

                    b.Property<int>("IdAnagrafica")
                        .HasColumnType("int");

                    b.Property<int>("IdViolazione")
                        .HasColumnType("int");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("IndirizzoViolazione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nominativo_Agente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdVerbale");

                    b.HasIndex("IdAnagrafica");

                    b.HasIndex("IdViolazione");

                    b.ToTable("Verbali");

                    b.HasData(
                        new
                        {
                            IdVerbale = 1,
                            DataTrascrizioneVerbale = new DateTime(2024, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataViolazione = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DecurtamentoPunti = 3,
                            IdAnagrafica = 1,
                            IdViolazione = 1,
                            Importo = 180.50m,
                            IndirizzoViolazione = "Via Garibaldi 12",
                            Nominativo_Agente = "Agente Rossi"
                        });
                });

            modelBuilder.Entity("PoliziaMunicipale.Models.Verbale", b =>
                {
                    b.HasOne("PoliziaMunicipale.Models.Anagrafica", "Anagrafica")
                        .WithMany("Verbali")
                        .HasForeignKey("IdAnagrafica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliziaMunicipale.Models.TipoViolazione", "TipoViolazione")
                        .WithMany("Verbali")
                        .HasForeignKey("IdViolazione")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anagrafica");

                    b.Navigation("TipoViolazione");
                });

            modelBuilder.Entity("PoliziaMunicipale.Models.Anagrafica", b =>
                {
                    b.Navigation("Verbali");
                });

            modelBuilder.Entity("PoliziaMunicipale.Models.TipoViolazione", b =>
                {
                    b.Navigation("Verbali");
                });
#pragma warning restore 612, 618
        }
    }
}
